---
# tasks file for haproxy
- name: installing haproxy software
  package:
      name: haproxy
      state: present
- name: copying the haproxy config file
  template:
         dest: "/etc/haproxy/haproxy.cfg"
         src: "haproxy.cfg.j2"
- name: starting haproxy services
  service:
        name: haproxy
        state: started
